#!/usr/bin/env python3
"""
Result persistence: JSON (machine), CSV (spreadsheet), Markdown (humans).

Layout, per scenario:

    <out>/<scenario>/summary.json     scenario config + per-replicate
                                      summaries + aggregates per scheduler
    <out>/<scenario>/nights.csv       per-night records (scheduler, seed, ...)
    <out>/<scenario>/README.md        human summary with the comparison table

Everything written here is SYNTHETIC PROJECTION — the writers stamp that on
every artifact so simulated numbers can never masquerade as production data.
"""

import csv
import dataclasses
import json
import os
from datetime import datetime, timezone

from sim import metrics as metrics_mod

DISCLAIMER = ("SYNTHETIC PROJECTION — generated by the fleet digital twin "
              "(sim/) from a seeded synthetic world. Not observed production "
              "data.")


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%MZ")


def write_scenario_results(out_dir: str, scenario, results_by_sched: dict,
                           notes: str = "") -> dict:
    """results_by_sched: scheduler -> [run result dict per seed]."""
    sdir = os.path.join(out_dir, scenario.name)
    os.makedirs(sdir, exist_ok=True)

    summaries = {sched: [metrics_mod.summarize_run(r) for r in runs]
                 for sched, runs in results_by_sched.items()}
    aggregates = {sched: metrics_mod.aggregate(s)
                  for sched, s in summaries.items()}

    payload = {
        "disclaimer": DISCLAIMER,
        "generated_at": _stamp(),
        "scenario": dataclasses.asdict(scenario),
        "aggregates": aggregates,
        "replicates": summaries,
    }
    with open(os.path.join(sdir, "summary.json"), "w") as f:
        json.dump(payload, f, indent=2, default=str)

    _write_nights_csv(os.path.join(sdir, "nights.csv"), results_by_sched)
    _write_markdown(os.path.join(sdir, "README.md"), scenario,
                    aggregates, notes)
    return payload


def _write_nights_csv(path: str, results_by_sched: dict) -> None:
    cols = ["scheduler", "seed", "night", "n_planned", "n_executed",
            "n_accepted", "expected_deliveries", "realized_value",
            "schedulable_value", "planned_minutes", "wasted_minutes",
            "distinct_targets", "transit_events", "transit_covered",
            "transit_mean_coverage", "utc_hours_covered", "mean_clear_frac"]
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["# " + DISCLAIMER])
        w.writerow(cols)
        for sched, runs in sorted(results_by_sched.items()):
            for run in runs:
                for rec in run["nights"]:
                    w.writerow([sched, run["seed"]]
                               + [rec.get(c, "") for c in cols[2:]])


def _write_markdown(path: str, scenario, aggregates: dict,
                    notes: str) -> None:
    ordered = sorted(
        aggregates.values(),
        key=lambda a: -(a.get("accepted_per_night", {}) or {}).get("mean", 0.0))
    lines = [
        f"# Scenario: {scenario.name}",
        "",
        f"> {DISCLAIMER}",
        f"> Generated {_stamp()}.",
        "",
        scenario.description,
        "",
        f"**World:** {scenario.n_nodes} nodes · {scenario.n_targets} catalog "
        f"targets · {scenario.nights} nights · epoch {scenario.epoch[:10]} · "
        f"replicates/seeds: "
        f"{next(iter(aggregates.values()), {}).get('seeds', [])}",
        "",
        "## Scheduler comparison (mean ± sd across seed replicates)",
        "",
        metrics_mod.comparison_table(ordered),
        "",
        "Columns: accepted = QC-passing (AAVSO-submittable) measurements; "
        "realized value = post-hoc information-cell value captured (same "
        "accounting for every scheduler); wasted minutes = scheduled dwell "
        "that produced no accepted measurement; gini = node-load inequality "
        "(0 = even).",
    ]
    if notes:
        lines += ["", "## Notes", "", notes]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
